package:
  name: {{ cookiecutter.project_name }}
  version: {{ cookiecutter.initial_version }}

source:
  fn: {{ cookiecutter.project_slug }}-{{ cookiecutter.initial_version }}.tar.gz
  url: {{ cookiecutter.sdist_url }}/{{ version }}/{{ name }}-{{ version }}.tar.gz
  # TODO: way to specify a hole or 
  sha256:

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - {{ cookiecutter.package_slug }} = {{ cookiecutter.package_slug }}.cli:cli

requirements:
  build:
    - python
    - setuptools
    - wheel

  host:
    - python
    
  run:
    - python
    

about:
  home: https://github.com/adicksonlab/wepy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Weighted ensemble (WE) framework for Python"
  doc_url: https://adicksonlab.github.io/wepy/
  dev_url: https://github.com/adicksonlab/wepy

extra:
  recipe-maintainers:
    - salotz
